### ISSUE TITLE
Discussion and Research Papers 

### ISSUE THREAD

**Issue by NabilBukhari** [nadjalc/CSSproject#1]
Please submit all the important research papers or discussion to the following issue,

**Comment by nadjalc** [comment]
https://www.kaggle.com/rounakbanik/ted-data-analysis
TED data set DESCRIPTIVE analysis example we can get ideas from

**Comment by NabilBukhari** [comment]
Study the Types of Correlation and their benefits (Pearson, Kendall, Spearman)

http://www.statisticssolutions.com/correlation-pearson-kendall-spearman/
